### ISSUE TITLE
error in train_sr.py when testing 

### ISSUE THREAD

**Issue by pjwwx** [vinthony/ghost-free-shadow-removal#19]
Traceback (most recent call last):
  File "train_sr.py", line 52, in <module>
    shadow_free_image,predicted_mask=build_aggasatt_joint(input,channel,vgg_19_path=vgg_19_path)
  File "/public/wuwenxuan/projects/ghost-free-shadow-removal-master/networks.py", line 143, in build_aggasatt_joint
    vgg19_features=build_vgg19(input[:,:,:,0:3]*255.0,vgg_19_path)
  File "/public/wuwenxuan/projects/ghost-free-shadow-removal-master/networks.py", line 78, in build_vgg19
    vgg_path=scipy.io.loadmat(vgg_path)
  File "/public/wuwenxuan/anaconda3/envs/shadow/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 222, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/public/wuwenxuan/anaconda3/envs/shadow/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/public/wuwenxuan/anaconda3/envs/shadow/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/public/wuwenxuan/anaconda3/envs/shadow/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, mode), True
TypeError: expected str, bytes or os.PathLike object, not dict

**Comment by vinthony** [comment]
Hi, thanks for your attention to our work.

This error often occurs when the path of VGG19 is not correct.

Please config it in the right place:

https://github.com/vinthony/ghost-free-shadow-removal/blob/0707b0a34a8cdca2fff956697755dab98c603d3b/train_sr.py#L34

Or you can try to run the demo from the command line via the introduction here:
https://github.com/vinthony/ghost-free-shadow-removal#3-demo-from-command-line-thanks-aliericcantona
