### ISSUE TITLE
ResourceExhaustedError when trying resolutions above 320 * 240 (W, H)

### ISSUE THREAD

**Issue by ahrooran-r** [vinthony/ghost-free-shadow-removal#33]
Hi, great paper. When testing the code with demp.py, I have encountered error ResourceExhaustedError when tried with 640 * 480 resolution (just testing. I didn't even train it)

I use a GTX 1650 gpu. I am very new to machine learning, So I don't quite understand why this happens. When I force PC to run on CPU, it works for larger images after long time. But not with GPU. Is it because my GPU can't handle it???

However, the shadow synthesis worked well for even larger images of 1920 * 1080 size. So why this doesn't work and what can I do to make it work on such images. Thanks in advance.

**Comment by vinthony** [comment]
yes, the main reason here is that the vgg19 feature extractor will spend a lot of GPU memory.

I would suggest that you try [our online demo](https://colab.research.google.com/drive/1cJ_dsBUXFaFtjoZB9gDYeahjmysnvnTq) for a fast test.

For training, I suggest that you can retrain our method without the VGG feature extraction.

**Comment by ahrooran-r** [comment]
Hi again,

is there a possibility to use this model without vgg19 as it takes much GPU as you mentioned. 
I tried commenting out 

    vgg19_features = build_vgg19(input[:, :, :, 0:3] * 255.0, vgg_19_path)
    for layer_id in range(1, 6):
        vgg19_f = vgg19_features['conv%d_2' % layer_id]
        input = tf.concat([tf.image.resize_bilinear(vgg19_f, (tf.shape(input)[1], tf.shape(input)[2])) / 255.0, input],
                          axis=3)

above part in method `build_aggasatt_joint `but that didn't work. How to remove the vgg part from the model. I want to avoid retraining as much as possible as it will take much time. How can I do this. Sorry I am very new to TF and ML. Can you give me any pointers as to move on,

The images I am trying to remove shadows are all document images of same type so I figured that a featurizer might not be necessary.

Thanks in advance.

**Comment by vinthony** [comment]
I think just removing the above lines as you mention will work fine.

any errors?

**Comment by ahrooran-r** [comment]
It works for the most part. But sometimes I get blacked out images. But now that you mentioned it, I checked the source images and the shadows are tricky indeed. The original model removed such shadows but the removed one didn't.

I guess vgg_19 is necessary for those type of shadows. Can you give me pointers on how to work on vgg_19 to optimize for performance??? using any similar models etc. By the way your model is the best I've tried when compared with others so far. 

Thanks in advance

**Comment by ahrooran-r** [comment]
So  commented out these lines:
![image](https://user-images.githubusercontent.com/46846338/139622006-e57a66ee-1544-4b60-9009-0b90cc66b791.png)

Now I got this error:

```
2 root error(s) found.
    (0) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[node save/Assign_143 (defined at E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
    (1) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[node save/Assign_143 (defined at E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	   [[save/RestoreV2/_228]]
```

Full error below:

 ```
 ---------------------------------------------------------------------------
  InvalidArgumentError                      Traceback (most recent call last)
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\client\session.py in _do_call(self, fn, *args)
     1364     try:
  -> 1365       return fn(*args)
     1366     except errors.OpError as e:
  
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
     1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  -> 1350                                       target_list, run_metadata)
     1351 
  
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
     1442                                             fetch_list, target_list,
  -> 1443                                             run_metadata)
     1444 
  
  InvalidArgumentError: 2 root error(s) found.
    (0) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[{{node save/Assign_143}}]]
    (1) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[{{node save/Assign_143}}]]
	   [[save/RestoreV2/_228]]
  0 successful operations.
  0 derived errors ignored.
  
  During handling of the above exception, another exception occurred:
  
  InvalidArgumentError                      Traceback (most recent call last)
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py in restore(self, sess, save_path)
     1289         sess.run(self.saver_def.restore_op_name,
  -> 1290                  {self.saver_def.filename_tensor_name: save_path})
     1291     except errors.NotFoundError as err:
  
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
      955       result = self._run(None, fetches, feed_dict, options_ptr,
  --> 956                          run_metadata_ptr)
      957       if run_metadata:
  
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
     1179       results = self._do_run(handle, final_targets, final_fetches,
  -> 1180                              feed_dict_tensor, options, run_metadata)
     1181     else:
  
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
     1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
  -> 1359                            run_metadata)
     1360     else:
  
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\client\session.py in _do_call(self, fn, *args)
     1383                     'disable_meta_optimizer = True')
  -> 1384       raise type(e)(node_def, op, message)
     1385 
  
  InvalidArgumentError: 2 root error(s) found.
    (0) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[node save/Assign_143 (defined at E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
    (1) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[node save/Assign_143 (defined at E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	   [[save/RestoreV2/_228]]
  0 successful operations.
  0 derived errors ignored.
  
  Original stack trace for 'save/Assign_143':
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
      app.start()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelapp.py", line 667, in start
      self.io_loop.start()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\asyncio\base_events.py", line 541, in run_forever
      self._run_once()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\asyncio\base_events.py", line 1786, in _run_once
      handle._run()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\asyncio\events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
      await self.process_one()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
      await dispatch(*args)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
      await result
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
      reply_content = await reply_content
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\ipkernel.py", line 345, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 2899, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 2944, in _run_cell
      return runner(coro)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 3170, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 3361, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\MSIUSE~1\AppData\Local\Temp/ipykernel_988/2486625114.py", line 8, in <module>
      saver_restore=tf.train.Saver([var for var in tf.trainable_variables()])
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
      self.build()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
      self._build(self._filename, build_save=True, build_restore=True)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
      build_restore=build_restore)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
      restore_sequentially, reshape)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 350, in _AddRestoreOps
      assign_ops.append(saveable.restore(saveable_tensors, shapes))
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saving\saveable_object_util.py", line 73, in restore
      self.op.get_shape().is_fully_defined())
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\ops\state_ops.py", line 227, in assign
      validate_shape=validate_shape)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\ops\gen_state_ops.py", line 66, in assign
      use_locking=use_locking, name=name)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
      op_def=op_def)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
      return func(*args, **kwargs)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
      attrs, op_def, compute_device)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
      op_def=op_def)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
      self._traceback = tf_stack.extract_stack()
  
  
  During handling of the above exception, another exception occurred:
  
  InvalidArgumentError                      Traceback (most recent call last)
  C:\Users\MSIUSE~1\AppData\Local\Temp/ipykernel_988/2486625114.py in <module>
        8 saver_restore=tf.train.Saver([var for var in tf.trainable_variables()])
        9 print('loaded '+idtd_ckpt.model_checkpoint_path)
  ---> 10 saver_restore.restore(sess,idtd_ckpt.model_checkpoint_path)
  
  E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py in restore(self, sess, save_path)
     1324       # We add a more reasonable error message here to help users (b/110263146)
     1325       raise _wrap_restore_error_with_msg(
  -> 1326           err, "a mismatch between the current graph and the graph")
     1327 
     1328   @staticmethod
  
  InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
  
  2 root error(s) found.
    (0) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[node save/Assign_143 (defined at E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
    (1) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,3,64] rhs shape= [1,1,1475,64]
	   [[node save/Assign_143 (defined at E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	   [[save/RestoreV2/_228]]
  0 successful operations.
  0 derived errors ignored.
  
  Original stack trace for 'save/Assign_143':
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
      app.start()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelapp.py", line 667, in start
      self.io_loop.start()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\asyncio\base_events.py", line 541, in run_forever
      self._run_once()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\asyncio\base_events.py", line 1786, in _run_once
      handle._run()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\asyncio\events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
      await self.process_one()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
      await dispatch(*args)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
      await result
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
      reply_content = await reply_content
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\ipkernel.py", line 345, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 2899, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 2944, in _run_cell
      return runner(coro)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 3170, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 3361, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\MSIUSE~1\AppData\Local\Temp/ipykernel_988/2486625114.py", line 8, in <module>
      saver_restore=tf.train.Saver([var for var in tf.trainable_variables()])
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
      self.build()
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
      self._build(self._filename, build_save=True, build_restore=True)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
      build_restore=build_restore)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
      restore_sequentially, reshape)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saver.py", line 350, in _AddRestoreOps
      assign_ops.append(saveable.restore(saveable_tensors, shapes))
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\training\saving\saveable_object_util.py", line 73, in restore
      self.op.get_shape().is_fully_defined())
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\ops\state_ops.py", line 227, in assign
      validate_shape=validate_shape)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\ops\gen_state_ops.py", line 66, in assign
      use_locking=use_locking, name=name)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
      op_def=op_def)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
      return func(*args, **kwargs)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
      attrs, op_def, compute_device)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
      op_def=op_def)
    File "E:\OpenSoftware\miniconda\envs\shadow_synthesis\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
      self._traceback = tf_stack.extract_stack()

```

Please help

**Comment by vinthony** [comment]
```
 InvalidArgumentError                      Traceback (most recent call last)
 C:\Users\MSIUSE~1\AppData\Local\Temp/ipykernel_988/2486625114.py in <module>
       8 saver_restore=tf.train.Saver([var for var in tf.trainable_variables()])
       9 print('loaded '+idtd_ckpt.model_checkpoint_path)
 ---> 10 saver_restore.restore(sess,idtd_ckpt.model_checkpoint_path)
```

it seems you have loaded the pre-trained model to the new graph. please remove the args about the pre-trained model path.

**Comment by ahrooran-r** [comment]
Wait. What I did was to comment out the lines and tested on a shadow image. Was my approach wrong?
Should I re-train the whole model after commenting out the lines before testing on a new image again?

**Comment by vinthony** [comment]
yes, the model is totally different. you need to retrain the network
